// src/components/ui/ProjectCard.jsx
import Reveal from './Reveal'

export default function ProjectCard({ project, idx, featured = false }) {
  return (
    <Reveal
      delay={Math.min(idx * 0.05, 0.25)}
      className={featured ? 'sm:col-span-2 lg:col-span-1' : ''}
    >
      <a
        href={project.github}
        target="_blank"
        rel="noreferrer"
        className="group relative flex h-full flex-col justify-between overflow-hidden border border-ink-200 bg-ink-0 p-7 transition-colors duration-300 hover:bg-ink-950 dark:border-ink-800 dark:bg-ink-950 dark:hover:bg-ink-50"
      >
        <div>
          <div className="mb-6 flex items-start justify-between">
            <span className="font-mono text-xs text-ink-400 transition-colors group-hover:text-ink-400 dark:text-ink-600 dark:group-hover:text-ink-500">
              {String(idx + 1).padStart(2, '0')}
            </span>
            <span className="flex items-center gap-2">
              {project.featured && (
                <span className="font-mono text-[10px] uppercase tracking-widest text-ink-400 transition-colors group-hover:text-ink-400 dark:text-ink-600 dark:group-hover:text-ink-500">
                  Featured
                </span>
              )}
              <svg
                viewBox="0 0 24 24"
                className="h-5 w-5 text-ink-950 transition-all duration-300 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-ink-0 dark:text-ink-50 dark:group-hover:text-ink-950"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.6"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M7 17 17 7M8 7h9v9" />
              </svg>
            </span>
          </div>

          <h3 className="font-display text-xl font-semibold tracking-tight text-ink-950 transition-colors group-hover:text-ink-0 dark:text-ink-50 dark:group-hover:text-ink-950">
            {project.title}
          </h3>
          <p className="mt-3 text-sm leading-relaxed text-ink-600 transition-colors group-hover:text-ink-300 dark:text-ink-400 dark:group-hover:text-ink-600">
            {project.description}
          </p>
        </div>

        <ul className="mt-6 flex flex-wrap gap-2">
          {project.tech.map((t) => (
            <li
              key={t}
              className="rounded-full border border-ink-200 px-2.5 py-1 font-mono text-[11px] text-ink-500 transition-colors group-hover:border-ink-700 group-hover:text-ink-300 dark:border-ink-800 dark:text-ink-400 dark:group-hover:border-ink-300 dark:group-hover:text-ink-600"
            >
              {t}
            </li>
          ))}
        </ul>
      </a>
    </Reveal>
  )
}

// src/components/ProjectCard.vue
<template>
  <div class="project-card">
    <div class="project-overlay">
      <a :href="project.github" target="_blank" rel="noopener noreferrer" class="github-btn">
        <svg class="icon" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
        </svg>
        View on GitHub
      </a>
    </div>
    
    <div class="project-content">
      <h3 class="project-title">{{ project.title }}</h3>
      <p class="project-description">{{ project.description }}</p>
      
      <div class="tech-stack">
        <span v-for="tech in project.tech" :key="tech" class="tech-tag">
          {{ tech }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { defineProps } from 'vue';

defineProps({
  project: {
    type: Object,
    required: true
  }
});
</script>

<style scoped>
.project-card {
  background: linear-gradient(135deg, #ffffff 0%, #f8fafc 100%);
  border-radius: 12px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.07);
  border: 1px solid #e5e7eb;
  transition: all 0.3s ease;
  height: 100%;
  display: flex;
  flex-direction: column;
  position: relative;
  overflow: hidden;
}

.dark .project-card {
  background: linear-gradient(135deg, #1f2937 0%, #111827 100%);
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
  border-color: #374151;
}

.project-card:hover {
  transform: translateY(-8px);
  box-shadow: 0 12px 24px rgba(59, 130, 246, 0.15);
}

.dark .project-card:hover {
  box-shadow: 0 12px 24px rgba(96, 165, 250, 0.2);
}

.project-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.85);
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  transition: opacity 0.3s ease;
  z-index: 10;
}

.project-card:hover .project-overlay {
  opacity: 1;
}

.github-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  background: rgba(255, 255, 255, 0.95);
  color: #111827;
  border-radius: 8px;
  text-decoration: none;
  font-weight: 600;
  transition: all 0.3s ease;
}

.github-btn:hover {
  background: #3b82f6;
  color: white;
  transform: scale(1.05);
}

.github-btn .icon {
  width: 1.25rem;
  height: 1.25rem;
}

.project-content {
  padding: 1.5rem;
  flex: 1;
  display: flex;
  flex-direction: column;
}

.project-title {
  font-size: 1.25rem;
  font-weight: 700;
  color: #111827;
  margin-bottom: 0.75rem;
}

.dark .project-title {
  color: #f9fafb;
}

.project-description {
  color: #6b7280;
  line-height: 1.6;
  margin-bottom: 1rem;
  flex: 1;
}

.dark .project-description {
  color: #9ca3af;
}

.tech-stack {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.tech-tag {
  padding: 0.25rem 0.75rem;
  background: #eff6ff;
  color: #3b82f6;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
}

.dark .tech-tag {
  background: #1e3a5f;
  color: #60a5fa;
}
</style>
